api/urls.py
from django.urls import path, include

app_name = 'API'

urlpatterns = [
    path('posts/', include('posts.api.urls'), name="posts"),
    path('notifications/', include('notifications.api.urls', namespace='Notifications')),
]

chats/urls.py
from django.urls import path

from chats.views import ChatsView, ChatView, chat

app_name = "Chats"
urlpatterns = [
    path('', ChatsView.as_view(), name="index"),
    path('<int:id>', ChatView.as_view(), name="show"),
    path('new/<int:user_id>', chat, name='new_chat'),
]

social_network/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import profile_info.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("django.contrib.auth.urls")),
    path("signup", profile_info.views.signup, name="signup"),
    path("profile/", include("profile_info.urls")),
    path("groups/", include("groups.urls")),
    path("user/", include("accounts.urls")),
    path('', include("posts.urls"), name='posts'),
    path('notifications/', include("notifications.urls", namespace="Notifications")),
    path('chats/', include("chats.urls", namespace="Chats")),
    path("api/", include("api.urls", namespace="API"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'libraries/bootstrap-4.6.0-dist/css/bootstrap.min.css' %}"
          crossorigin="anonymous"/>
    <script src="https://kit.fontawesome.com/7f1419bc41.js" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.0/moment.min.js" crossorigin="anonymous">
    </script>
    <style>
        .notify-drop {
            width: 40vw;
            left: -31vw;
            cursor: auto;
            z-index: 10000;
        }

        body {
            background-color: #dbd8d8;
        }

        .custom-style {
            background-color: #dfe6e9 !important;
        }

        .border-3 {
            border-width: 3px !important;
        }


        .notification-item:hover {
            background-color: lightblue;
            cursor: pointer;
        }

        @media (max-width: 992px) {
            .notify-drop {
                width: 90vw;
                left: initial;
            }

        }
    </style>
    {% block styles %}{% endblock %}
    <title>{% block title %}{% endblock %} | Social Network</title>
</head>
<body>

{### MODAL ###}
<div class="modal fade" id="notificationAlert" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Connection lost</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Connection to socket lost please refresh page.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
    <a class="navbar-brand ml-5" href="{% url 'post-list' %}">Social Network</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'post-list' %}"><i class="fas fa-newspaper"></i> Home <span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == 'profile_index' %} active {% endif %}">
                <a class="nav-link"
                   href="{% url 'profile_index' request.user.id %}"><i
                        class="fas fa-user-circle"></i> {{ request.user.username }}</a>
            </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle
                    {% if request.resolver_match.url_name == 'friend_requests' %} active {% endif %}
                    {% if request.resolver_match.url_name == 'get_friends' %} active {% endif %}"
               href="#" id="navbarDropdownMenuLink" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-friends"></i> Friends
            </a>
            <div class="dropdown-menu rounded" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item {% if request.resolver_match.url_name == 'friend_requests' %} active {% endif %}"
                   href="{% url 'friend_requests' %}"><i class="fas fa-people-arrows"></i> Friend Requests</a>
                <a class="dropdown-item {% if request.resolver_match.url_name == 'get_friends' %} active {% endif %}"
                   href="{% url 'get_friends' %}"><i class="fas fa-user-friends"></i> My Friends</a>
            </div>
            </li>

            <li class="nav-item {% if request.resolver_match.url_name == 'index' %}active{% endif %}">
                <a class="nav-link"
                   href="{% url 'Chats:index' %}"><i class="fas fa-comment-dots"></i> Chats</a>
            </li>
            <li class="nav-item dropdown
                    {% if request.resolver_match.url_name == 'groups_index' %}
                    active
                    {% elif request.resolver_match.url_name == 'groups_my_groups' %}
                    active
                    {% elif request.resolver_match.url_name == 'groups_joined' %}
                    active
                    {% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-users"></i> Groups
                </a>
                <div class="dropdown-menu rounded" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item {% if request.resolver_match.url_name == 'groups_index' %} active {% endif %}"
                       href="{% url 'groups_index' %}"><i class="fas fa-users"></i> All Groups</a>
                    <a class="dropdown-item {% if request.resolver_match.url_name == 'groups_my_groups' %} active {% endif %}"
                       href="{% url 'groups_my_groups' %}"><i class="fas fa-plus-circle"></i> Created Groups</a>
                    <a class="dropdown-item {% if request.resolver_match.url_name == 'groups_joined' %} active {% endif %}"
                       href="{% url 'groups_joined' %}"><i class="fas fa-sign-in-alt"></i> Joined Groups</a>
                </div>
        </ul>
        {% if request.user.is_authenticated %}
            <ul class="nav btn btn-info ml-auto mr-4">
                <li class="dropdown notify-drop-button">
                    <a href="#" class="text-light text-decoration-none font-weight-bold p-2"
                       data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Notification
                        <span class="badge badge-danger notification notification-number">0</span>
                    </a>
                    <ul class="dropdown-menu notify-drop">
                        <!-- notify content -->
                        <div class="drop-content overflow-auto" style="height: 500px"></div>
                    </ul>
                </li>

            </ul>
        {% endif %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link bg-primary rounded-lg text-white" href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container-fluid">
    {% block content %}{% endblock %}
</div>
{% block scripts %}{% endblock %}
<script src="{% static 'libraries/jquery-3.5.1/jquery-3.5.1.slim.min.js' %}"
        crossorigin="anonymous"></script>
<script src="{% static 'libraries/bootstrap-4.6.0-dist/js/bootstrap.bundle.min.js' %}"
        crossorigin="anonymous"></script>
{% if request.user.is_authenticated %}
    <script>
        const notificationNumber = $(".notification-number").first()
        const renderNotification = (detail, sorted = true) => {
            if (!detail.is_seen) {
                notificationNumber.html(Number(notificationNumber.html()) + 1)
            }
            const fromNow = moment(detail.created_at).fromNow()
            const dropContent = $('.drop-content');
            const createdElement = $("<div class='row ml-3 pr-4 notification-item p-2'><div class='col-11'></div></div>")
                .append(
                    $(`<a class="text-decoration-none w-100" href="${detail.formatted_redirect_to}"></a>`).append(
                        `<div class="d-flex justify-content-between"><div class="font-weight-bold">${detail.formatted_title}</div><div>${fromNow}</div</div>`,
                        `<div class="text-dark">${detail.formatted_message}</div>`))
                .add('<hr>')
            if (sorted) {
                dropContent.append(createdElement)
            } else {
                dropContent.prepend(createdElement)
            }

        }
        $(document).ready(function () {
            const notificationsWebSocket = new WebSocket(`ws://${window.location.host}/ws/notifications/`)
            notificationsWebSocket.onmessage = event => {
                renderNotification(JSON.parse(event.data).message, false)
                const audio = new Audio("{% static 'notifications/insight-578.mp3' %}");
                audio.play();
            }
            notificationsWebSocket.onclose = event => $("#notificationAlert").modal('show');

            fetch('/api/notifications')
                .then(response => response.json())
                .then(responseObj => responseObj.detail.forEach(function (elem) {
                    renderNotification(elem)
                }))

            $(".notify-drop-button").click(event => {
                if (notificationsWebSocket.readyState !== WebSocket.CLOSED) {
                    $(".notification-number").html(0)
                    notificationsWebSocket.send(JSON.stringify({notification: "seen"}))
                }
            })
        })
    </script>
{% endif %}
</body>
</html>

templates/layouts/plain.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"/>
    <script src="https://kit.fontawesome.com/7f1419bc41.js" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.0/moment.min.js" crossorigin="anonymous">
    </script>
    <style>
        .notify-drop {
            width: 40vw;
            left: -31vw;
            cursor: auto;
            z-index: 10000;
        }

        body {
            background-color: #dbd8d8;
        }
    .logo{
        width:100px;
    }
        .custom-style {
            background-color: #dfe6e9 !important;
        }
.btn-cont{
    position: absolute;
    top:40%;
    right:0%;
    transform: translateY(-40%);
}
.home-img{
    position: absolute;
    top:30%;
    left:5%;
    transform: translateY(-30%);
}
    </style>
    {% block styles %}{% endblock %}
    <title>{% block title %}{% endblock %} | Social Network</title>
</head>
<body>

<div class="container p-3 position-relative">
            {% block content %}{% endblock %}
</div>
{% block scripts %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

</body>
</html>