api/urls.py
from django.urls import path, include

app_name = 'API'

urlpatterns = [
    path('posts/', include('posts.api.urls'), name="posts"),
    path('notifications/', include('notifications.api.urls', namespace='Notifications')),
]

chats/urls.py
from django.urls import path

from chats.views import ChatsView, ChatView, chat

app_name = "Chats"
urlpatterns = [
    path('', ChatsView.as_view(), name="index"),
    path('<int:id>', ChatView.as_view(), name="show"),
    path('new/<int:user_id>', chat, name='new_chat'),
]

profile_info/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('<user_id>', views.index, name="profile_index"),
    path('add_friend/<user_id>', views.add_friend, name="add_friend"),
    path('edit/<int:user_id>', views.edit, name="edit"),
    path('edit/password/<int:user_id>', views.edit_pass, name="edit_pass"),
]

social_network/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import profile_info.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("django.contrib.auth.urls")),
    path("signup", profile_info.views.signup, name="signup"),
    path("profile/", include("profile_info.urls")),
    path("groups/", include("groups.urls")),
    path("user/", include("accounts.urls")),
    path('', include("posts.urls"), name='posts'),
    path('notifications/', include("notifications.urls", namespace="Notifications")),
    path('chats/', include("chats.urls", namespace="Chats")),
    path("api/", include("api.urls", namespace="API"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_info/models.py
from django.db import models
from accounts.models import User


class Profile(models.Model):
    GENDER = (
        ("male", "male"),
        ("female", "female"),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=10, choices=GENDER, default="male")
    date_of_birth = models.DateField(null=True, blank=True)
    profile_image = models.ImageField(null=False, blank=False,
                                      upload_to='users/images/', default='images/default.jpg')


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField()
    uploaded_at = models.DateTimeField(auto_now_add=True)


# class Friends(models.Model):
#     pass

profile_info/forms.py
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User
from django import forms
from django.forms import PasswordInput, EmailInput, inlineformset_factory

from profile_info.models import Profile, Document


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class EditProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.', )
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)


class EditPassForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('password1', 'password2')


class DateInput(forms.DateInput):
    input_type = 'date'


class ProfileImage(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileImage, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control p-1'

    class Meta:
        model = Profile
        fields = ('profile_image',)
        exclude = ['user']


class ProfileForm(forms.ModelForm):
    # date_of_birth = forms.DateField(widget=DateInput)
    # profile_image = forms.ImageField(required=False, help_text='Optional.')

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

profile_info/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from posts.models import Post
from .forms import ProfileForm, SignUpForm, EditProfileForm, EditPassForm, ProfileImage
from .utils import get_index_context


def signup(request):
    form = SignUpForm(request.POST or None)
    profile = ProfileForm(request.POST or None)
    if request.method == "POST":

        if form.is_valid() and profile.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            profile = ProfileForm(request.POST, request.FILES, instance=user.profile)
            profile.save()
            if user:
                login(request, user)
                return redirect("profile_index", user.id)
            else:
                print(form.errors)
    return render(request, "registration/signup.html", {
        "form": form,
        "profile": profile,
    })


@login_required
def index(request, user_id):
    context = get_index_context(request, user_id)
    return render(request, 'profile_info_views/index.html', context)


@login_required
def edit(request, user_id):
    user = request.user
    profile = user.profile
    user_form = EditProfileForm(request.POST or None, instance=user)
    image_form = ProfileImage(request.POST or None, files=request.FILES, instance=profile)
    if user_form.is_valid() and image_form.is_valid():
        image_form.save()
        user_form.save()
        return redirect('profile_index', user_id)
    context = {"form": user_form, "profile": image_form, "user": user}
    return render(request, 'profile_info_views/edit.html', context)


@login_required
def edit_pass(request, user_id):
    user = request.user
    pass_form = EditPassForm(request.POST or None, instance=user)
    if pass_form.is_valid():
        pass_form.save()
        login(request, user)
        return redirect('profile_index')
    return render(request, 'profile_info_views/editPass.html', {
        "form": pass_form,
        "user": user
    })


@login_required
def add_friend(request, user_id):
    print(user_id)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

profile_info/templates/profile_info_views/edit.html
{% extends "layouts/base.html" %}

{% block styles %}
    <style>
        body {
            background-color: #dbd8d8;
        }

        .custom-style {
            background-color: #dfe6e9 !important;
        }

        .border-3 {
            border-width: 3px !important;
        }
    </style>
{% endblock %}
{% block title %}
    Profile Info
{% endblock %}

{% block content %}


    <div class="w-50 mx-auto my-4 p-5 rounded-lg custom-style">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ field.label }}: {{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}


        {% if profile.errors %}
            {% for field in profile %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ field.label }}: {{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in profile.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}


        <form action="{% url 'edit' user.id %}" method="POST" enctype="multipart/form-data"
        >
            {% csrf_token %}

            <div class="form-group">
                <img class="rounded-circle border border-primary border-3"
                     src="{{ user.profile.profile_image.url }}" height="100px" width="100px" alt="profile_pic">
            </div>

            {% for field in profile.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}

            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}

            <div class="form-group">
                <label for="id_dob">Date of Birth:</label>
                <input id="id_dob" disabled class="form-control" value="{{ user.profile.date_of_birth }}"/>
            </div>

            <div class="form-group">
                <label for="id_gender">Gender:</label>
                <input id="id_gender" disabled class="form-control" value="{{ user.profile.gender }}"/>
            </div>

            <button class="btn btn-primary btn-block" type="submit">Update</button>
        </form>
    </div>
{% endblock %}

profile_info/templates/profile_info_views/editPass.html
{% extends "layouts/base.html" %}

{% block styles %}
    <style>
        body {
            background-color: #dbd8d8;
        }

        .custom-style {
            background-color: #dfe6e9 !important;
        }
    </style>
{% endblock %}

{% block title %}
    Profile Info
{% endblock %}

{% block content %}
    <div class="w-75 mx-auto my-4 p-5 rounded-lg custom-style">
        <div class="form-group mx-auto mt-4 w-50">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.label }}: {{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <form action="{% url 'edit_pass' user.id %}" method="POST" class="mx-auto w-50">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_password1">Password:</label>
                <input type="password" name="password1" class="form-control"
                       autocomplete="new-password" id="id_password1">
                <div id="passwordHelpBlock" class="form-text">
                    <small>
                        Your password must be 8-20 characters long, contain letters and numbers, and must not contain
                        spaces, special characters, or emoji.
                    </small>
                </div>
            </div>

            <div class="form-group">
                <label for="id_password2">Password Confirmation:</label>
                <input type="password" name="password2" class="form-control"
                       autocomplete="new-password" id="id_password2">
                <small>
                    Confirmation Password must be the same.
                </small>
            </div>
            <button class="btn btn-primary" type="submit">Update</button>
        </form>
    </div>
{% endblock %}

profile_info/templates/profile_info_views/index.html
{% extends "layouts/base.html" %}

{% block styles %}
    <style>
        body {
            background-color: #dbd8d8;
        }

        .custom-style {
            background-color: #dfe6e9 !important;
        }

        .border-3 {
            border-width: 3px !important;
        }
    </style>
{% endblock %}

{% block title %}
    Profile Info
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col col-md-3 bg-light my-4 p-2 rounded-lg custom-style">
                <div class="mt-5 text-center">
                    <img class="rounded-circle border border-primary border-3"
                         src="{{ user.profile.profile_image.url }}" height="200px" width="200px" alt="profile_pic">
                </div>
                {% if request.user.id == user.id %}
                    <div class="w-100 d-flex justify-content-center mt-5">
                        <a class="btn btn-success mr-2" href="{% url 'edit' user.id %}">Edit</a>
                        <a class="btn btn-warning" href="{% url 'edit_pass' user.id %}">Change Password</a>
                    </div>
                {% else %}
                    <div class="w-75 mx-auto mt-5">
                        {% if friend.approved %}
                            <button class="btn btn-success btn-block"><i class="fas fa-people-arrows"></i> Already
                                Friends
                            </button>
                        {% elif exists and not friend.approved %}
                                <button class="btn btn-outline-warning btn-block">
                                    Request Pending
                                </button>
                                <a class="btn btn-outline-danger btn-block"
                                    href="{% url 'cancel_friend_request' friend.id user.id %}">
                                    Cancel Request
                                </a>
                        {% elif not exists %}
                            <a class="btn btn-outline-success btn-block"
                               href="{% url 'send_friend_request' user.id %}">Add Friend</a>
                        {% endif %}


                        <a class="btn btn-outline-info btn-block"
                           href="{% url 'Chats:new_chat' user.id %}">Send Message</a>
                    </div>
                {% endif %}
            </div>
            <div class="col ml-2 col-md-4 bg-light my-4 p-2 rounded-lg custom-style">
                <div class="p-3 mt-">
                    <h2 class="text-primary">Profile Info: </h2>
                    <div class="d-flex align-items-center">
                        <h3 class="p-2">Username: </h3>
                        <h5 class="p-2">{{ user.username }}</h5>
                    </div>
                    <div class="d-flex align-items-center">
                        <h3 class="p-2">First Name: </h3>
                        <h5 class="p-2">{{ user.first_name }}</h5>
                    </div>
                    <div class="d-flex align-items-center">
                        <h3 class="p-2">Last Name: </h3>
                        <h5 class="p-2">{{ user.last_name }}</h5>
                    </div>
                    <div class="d-flex align-items-center">
                        <h3 class="p-2">Email: </h3>
                        <h5 class="p-2">{{ user.email }}</h5>
                    </div>

                    <div class="d-flex align-items-center">
                        <h3 class="p-2">Gender: </h3>
                        <h5 class="p-2">{{ user.profile.gender }}</h5>
                    </div>
                    <div class="d-flex align-items-center">
                        <h3 class="p-2">Date of Birth: </h3>
                        <h5 class="p-2">{{ user.profile.date_of_birth }}</h5>
                    </div>

                </div>
            </div>
            <div class="col ml-2 col-md-4 bg-light my-4 p-2 rounded-lg custom-style">
                <form method="GET" action="">
                    <div class="p-2">
                        {{ filter.form }}
                        <button type="submit" class="btn btn-primary p-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-search" viewBox="0 0 16 16">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                            </svg>
                            Search
                        </button>
                    </div>
                    <div class="p-2">
                        {% for user in users %}
                            <h5><a href="{% url 'profile_index' user.id %}" class="d-block">{{ user.username }}</a></h5>
                        {% endfor %}
                    </div>
                </form>
            </div>
        </div>
        <div class="w-75 mx-auto my-4 p-5 rounded-lg custom-style">
        <div class="w-75 mx-auto text-center">
            <h2>Posts</h2>
        </div>
        {% for post in post_list %}
            <div class="bg-light rounded-lg py-4 my-4 custom-hover-list">
                <div class="row justify-content-center mt-3">
                    <div class="col-3 text-center">
                        <img class="rounded-circle border border-primary border-3"
                             src="{{ post.author.profile.profile_image.url }}" width="100" height="100" alt="image">
                    </div>
                    <div class="col position-relative">
                        <h4 class="text-primary"><strong><i class="fas fa-at"></i>{{ post.author }}</strong></h4>
                        <div class="d-flex">
                            <i class="far fa-newspaper"></i>&nbsp
                            <small class="text-muted">
                                {{ post.created_at | timesince }} ago <i class="fas fa-clock fa-xs"></i>
                            </small>
                        </div>

                        <p class="text-break">{{ post.body }}</p>

                        <a class="stretched-link" href="{% url 'post-detail' post.pk %}"></a>
                    </div>
                    <div class="d-flex flex-row mr-4">
                        <form method="POST" action="{% url 'like' post.pk %}">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button style="background-color: transparent; border: none; box-shadow: none;"
                                    type="submit"><i
                                    class="fas fa-thumbs-up"></i> <span>{{ post.likes.all.count }}</span></button>
                        </form>

                        <form method="POST" action="{% url 'dislike' post.pk %}">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button style="background-color: transparent; border: none; box-shadow: none;"
                                    type="submit"><i
                                    class="fas fa-thumbs-down"></i> <span>{{ post.dislikes.all.count }}</span></button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>

{% endblock %}